# Generated by Django 5.0.3 on 2024-05-11 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('related_doctor_id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'doctor_id must be exactly 8 digits')])),
                ('assistantName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicName', models.CharField(max_length=50)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorIMG', models.ImageField(blank=True, null=True, upload_to='DoctorIMG/')),
                ('doctorName', models.CharField(max_length=100)),
                ('doctor_id', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'doctor_id must be exactly 8 digits')])),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.clinic')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.departments')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=100)),
                ('hospitalIMG', models.ImageField(blank=True, null=True, upload_to='HospitalIMG/')),
                ('description_about_hospital', models.TextField()),
                ('clinics', models.ManyToManyField(to='application.clinic')),
                ('departments', models.ManyToManyField(to='application.departments')),
                ('doctors', models.ManyToManyField(related_name='hospitals', to='application.doctor')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.location')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.hospital'),
        ),
        migrations.CreateModel(
            name='Transform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('reportIMG', models.ImageField(blank=True, null=True, upload_to='reportIMG/')),
                ('reportText', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('departments', models.ManyToManyField(to='application.hospital')),
            ],
        ),
    ]
