# Generated by Django 5.0.3 on 2024-05-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_departments_hospital_available_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='clinics',
            new_name='clinicsId',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='doctors',
            new_name='doctorsId',
        ),
    ]
