# Generated by Django 5.0.3 on 2024-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_appointment_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
