# Generated by Django 5.0.3 on 2024-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_hospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='assistant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='assistant_requested',
            field=models.BooleanField(default=False),
        ),
    ]
