# Generated by Django 5.0.3 on 2024-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_assistant_email_doctor_email_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='assistantIMG',
            field=models.ImageField(blank=True, null=True, upload_to='AssistantIMG/'),
        ),
    ]
