# Generated by Django 5.0.3 on 2024-05-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_assistant_assistantimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='clinic',
            new_name='clinic_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='specialization',
            new_name='specialization_id',
        ),
    ]
