# Generated by Django 5.0.3 on 2024-05-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_rename_clinic_id_appointment_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transform',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.hospital'),
        ),
        migrations.RemoveField(
            model_name='transform',
            name='departments',
        ),
        migrations.AddField(
            model_name='transform',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.departments'),
        ),
    ]
