# Generated by Django 5.0.3 on 2024-05-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_transform_hospital_remove_transform_departments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transform',
            old_name='departments',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='transform',
            name='reportText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
