# Generated by Django 5.0.3 on 2024-05-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_rename_departments_transform_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transform',
            old_name='department',
            new_name='specialization',
        ),
    ]
