# Generated by Django 5.0.3 on 2024-05-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_rename_department_transform_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transform',
            name='specialization',
        ),
    ]
